fields:
- key: related-info
  type: info
  content: "## see [this page](https://gohugo.io/content-management/related/#configure-related-content) from the Hugo docs for more details."
- key: includeNewer
  title: Include Newer entries
  type: boolean
  default: false
  tip: "If enabled, more recent content can be found as related. Has the potential downside that \"related\" lists for a given content item may change over time as new content is added to the site."
- key: threshold
  title: Relatedness threshold
  type: slider
  step: 1
  min: 0
  max: 100
  default: 80
  tip: "Lower values yield more, but maybe not so relevant, matches. Default: 80"
- key: toLower
  title: Lower case keywords before matching
  type: boolean
  default: false
  tip: May give more accurate results at a slight performance penalty. Overridden by specific index configuration.
- key: empty-vpqkmc
  type: empty-line
- key: indices
  title: Indices
  type: accordion
  groupdata: true
  fields:
  - key: type
    title: Type of index
    type: select
    default: basic
    options:
    - basic
    - fragments
  - key: name
    title: Name
    type: string
    tip: Matches the frontmatter entry that is used to relate content items
  - key: weight
    title: Weight
    type: slider
    default: 25
    step: 1
    min: -100
    max: 100
    tip: Indicates how important a single parameter is, relative to the others. Value of 0 effectively turns an index off.
  - key: empty-qsdozienc
    type: empty-line
  - key: extraOptions
    title: Extra Options
    type: section
    groupdata: false
    fields:
    - key: cardinalityThreshold
      title: Cardinality Threshold
      type: slider
      step: 1
      min: 0
      max: 100
      default: 0
      tip: "If between 1 and 100, discards all keywords used in more than that percent of content from match search. A value of 0 means no keyword is discarded in this way. Default: 0"
    - key: applyFilter
      title: (Fragments only) Filter matches
      type: boolean
      default: false
      tip: "Only used for \"fragments\" indices"
    - key: pattern
      title: (Date only) Matching timespan
      type: select
      tip: Restricting to month may be a better option for busier sites
      default : "2006"
      options:
      - key: "2006"
        text: Y - Match with all content published the same year
      - key: "200601"
        text: M - Match (only) with content published the same month